type Input = { name:string; email:string; message:string; topic:string; subject:string; phone:string; emailSubject:string; text:string };
const esc = (v:string) => v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");

export function buildBrandedContactEmail(input: Input) {
  const { name,email,message,topic,subject,phone,emailSubject,text } = input;
  const reference = `A4L-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
  const receivedAt = new Intl.DateTimeFormat("en-CA", { dateStyle:"medium", timeStyle:"short", timeZone:"America/Toronto" }).format(new Date());
  const html = `<!doctype html><html lang="en"><body style="margin:0;padding:0;background:#f8fafc;font-family:Arial,Helvetica,sans-serif;color:#1f2937"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f8fafc"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:600px;background:#fff;border:1px solid #e2e8f0"><tr><td background="https://ask4loan.ca/assets/email/contact-header-bg.jpg" style="padding:76px 32px;background:#10b981 url('https://ask4loan.ca/assets/email/contact-header-bg.jpg') center/cover;color:#fff;text-align:center"><h1 style="margin:0;font-size:34px;line-height:1.15;font-weight:700;letter-spacing:-.8px;color:#fff">New message from ${esc(name)}</h1><div style="margin-top:14px;font-size:16px;line-height:1.4;color:#fff">${esc(subject || topic)}</div></td></tr><tr><td style="padding:30px 32px 12px"><div style="font-size:11px;line-height:1.5;font-weight:700;color:#10b981">${esc(receivedAt)} &nbsp;&middot;&nbsp; ${reference}</div><h2 style="margin:16px 0 0;font-size:26px;line-height:1.25;font-weight:700;letter-spacing:-.4px;color:#1f2937">${esc(subject || topic)}</h2><div style="margin-top:20px;font-size:16px;line-height:1.65;white-space:pre-wrap;color:#475569">${esc(message)}</div><div style="margin-top:22px;font-size:11px;line-height:1.5;color:#64748b"><a href="mailto:${esc(email)}" style="color:#059669;text-decoration:underline">${esc(email)}</a>${phone ? `<span style="padding:0 7px;color:#cbd5e1">&middot;</span><span>${esc(phone)}</span>` : ""}</div></td></tr><tr><td align="center" style="padding:24px 32px 28px"><img src="https://ask4loan.ca/logo.svg" width="76" alt="Ask4Loan" style="display:block;width:76px;height:auto;margin:0 auto;border:0"><div style="margin-top:14px;font-size:11px;line-height:1.6"><a href="https://ask4loan.ca/privacy-policy" style="color:#1f2937">Privacy Policy</a><span style="padding:0 7px;color:#cbd5e1">|</span><a href="https://ask4loan.ca/terms-of-use" style="color:#1f2937">Terms of Use</a></div><div style="margin-top:14px;font-size:10px;line-height:1.65;color:#94a3b8">Sent securely from the Ask4Loan contact form.<br>Never request passwords, banking credentials, or security codes by email.</div></td></tr></table></td></tr></table></body></html>`;
  return { subject: emailSubject, html, text: `${text}\n\nReference: ${reference}` };
}
